# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# compile C with C:/msys64/mingw64/bin/cc.exe
# compile CXX with C:/msys64/mingw64/bin/c++.exe
C_DEFINES = -DGLFW_INCLUDE_NONE -D_CRT_SECURE_NO_WARNINGS

C_INCLUDES = @CMakeFiles/vulkan_renderer.dir/includes_C.rsp

C_FLAGS = -std=gnu99  -O3  -march=native -funroll-loops -mfpmath=sse -msse2 -msse3 -mssse3 -ffast-math  -Wno-format-y2k  -fno-strict-aliasing   -flto  -ffunction-sections 

CXX_DEFINES = -DGLFW_INCLUDE_NONE -D_CRT_SECURE_NO_WARNINGS

CXX_INCLUDES = @CMakeFiles/vulkan_renderer.dir/includes_CXX.rsp

CXX_FLAGS = 

